BUGFIX/MEDIUM(gridinit): No longer use the library `gridinitcmd.py`
 ##### SUMMARY
This library is deprecated and the message `UnboundLocalError: local variable 'subaction' referenced before assignment` shows a bug when the output is empty

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION
```console
TASK [role_under_test : Reload gridinit] ***************************************
Wednesday 08 May 2019  19:57:23 +0000 (0:00:00.260)       0:02:03.089 *********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'subaction' referenced before assignment
fatal: [localhost]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/tmp/ansible_DLOK76/ansible_module_gridinitcmd.py", line 222, in <module>
        main()
      File "/tmp/ansible_DLOK76/ansible_module_gridinitcmd.py", line 213, in main
        take_action_on_processes(processes, lambda s: True, 'reload', 'reload')
      File "/tmp/ansible_DLOK76/ansible_module_gridinitcmd.py", line 159, in take_action_on_processes
        module.exit_json(changed=True, name=subaction, state=state, msg=ret_format)
    UnboundLocalError: local variable 'subaction' referenced before assignment
  module_stdout: |-
    KEY
  msg: MODULE FAILURE

```